name: 小C的博客
# url: http://matt.harzewski.com
# url:  https://jun-zz.github.io/
url: https://jun-zz.github.io/jekyll-theme-basically-basic/
description: Insert tagline here

permalink: /themes/:title/

gems: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
